[DX-40] Add repository settings, identities and a WIP workflow to create repositories
pagopa/dx-typescript pull request #1
Opened 2024-03-01 11:13 UTC by Krusty93

2024-03-04 15:53 UTC, gunzip commented
may you add a description?

2024-03-08 17:20 UTC, balanza commented
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏

> A pipeline to create new public repositories within PagoPA org

Is this intended to be used from this repository?

2024-03-08 17:24 UTC, Krusty93 commented
> **question:** ‏
> 
> > A pipeline to create new public repositories within PagoPA org
> 
> Is this intended to be used from this repository?

I see this PR as an MVP. If it works and we like it, it'd be moved to the main DX repository (not created yet).

2024-03-11 12:58 UTC, gunzip requested changes
We need some documentation before merging this one. At the bare minimum we should 
1. make it very clear what are the moving parts (what values are suppoosed to be changed by the end user of these files)
2. add a comment for the more obscure parts
3. add a paragrah into the README with the user manual (usage)

2024-03-11 18:45 UTC, Krusty93 commented
> We need some documentation before merging this one. At the bare minimum we should
> 
> 1. make it very clear what are the moving parts (what values are suppoosed to be changed by the end user of these files)
> 2. add a comment for the more obscure parts
> 3. add a paragrah into the README with the user manual (usage)

Almost nothing. These configuration includes federation with Azure to run pipelines (once done there is nothing to change) and repository settings (same). 
As @lucacavallaro said today, this is a playground repo so I wouldn't focus into documentation too much, until the code is not landing in official dx repo

I would like instead hearing a feedback from you guys about the content (especially repo settings since everybody is involved)

2024-03-13 10:18 UTC, gunzip commented on .github/workflows/cd_repository_deploy.yaml
> +          echo "terraform_version=$(cat .terraform-version)" >> $GITHUB_OUTPUT
may this introduce a security issue in case someone

2024-03-14 11:56 UTC, gunzip approved these changes

2024-03-14 11:56 UTC, gunzip commented on .github/workflows/repository_builder.yaml
> +      - name: Replace placeholders
I'd postpone this to another PR / step

2024-03-14 11:56 UTC, gunzip commented on .github/workflows/repository_builder.yaml
> +        working-directory: repo/infra/repository
```suggestion
        # we assume that the template repository contains this directory
        working-directory: repo/infra/repository
```

2024-03-15 09:49 UTC, merged