[DEVEX-104] Setup Yarn
pagopa/dx-typescript pull request #3
Opened 2024-03-11 11:57 UTC by lucacavallaro

# Use yarn with Plug'n'Play

Date: 2024-03-11

## Status

Accepted

## Context

**Plug'n'Play** is an installation strategy, alternative to the classic resolution algorithm used by `npm`/`node.js` with `node_modules`, that simplify working on monorepo and large javascript codebases.

For our use cases, `pnp` has two major advantages over the classic approach:

1. An efficient dependency resolution algorithm and a global cache that allows dependency reuse (the developer installs dependencies only once on his machine, regardless of how many projects it is used in).

2. Catch _ghost dependencies_ (dependencies that are not listed in `package.json`), ensuring that each workspace declares all dependencies it uses.

See the documentation for more details https://yarnpkg.com/features/pnp

## Decision

We decided to enable `plug'n'play` with global cache on our yarn setup.

2024-03-11 12:51 UTC, gunzip commented
When are we supposed to run `yarn dlx @yarnpkg/sdks` to update them? I'dd add a line into the README.

2024-03-11 13:21 UTC, lucacavallaro commented
> When are we supposed to run `yarn dlx @yarnpkg/sdks` to update them? I'dd add a line into the README.

I don't have a clear idea at the moment, I don't even know if it will be necessary. Perhaps the right time is during the periodic update of dependencies.

2024-03-13 15:00 UTC, gunzip commented
needs rebasing on main

2024-03-15 10:35 UTC, balanza requested changes
I think some docs may be useful

2024-03-15 10:35 UTC, balanza commented on templates/monorepo/README.md
> +# TypeScript Monorepo Template
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** I'd add some documentation about it to give developers a little context. Mainly any requirements/configurations, caveats, and little context about files in `.yarn/sdk` folder.
‏

2024-04-15 15:31 UTC, closed without merging